### ISSUE TITLE
Scanner-Interface verletzt / errorMessage fehlt

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#10]
Folgender Output bei einem HEARTBLEED-Test:

```json
{
   "name": "HEARTBLEED_VULNERABLE",
   "hasError": true,
   "errorMessage": null,
   "score": 100,
   "scoreType": "success",
   "testDetails": null
 }
```

Es wird `hasError: true` gesetzt, jedoch keine Fehlermeldung ausgegeben.

Bitte Fehlermeldung implementieren und dies ebenfalls bei den anderen Tests sicherstellen.

**Comment by Lednerb** [comment]
Ebenfalls der Fall bei:

```json
{
   "name":"BLEICHENBACHER_VULNERABLE",
   "hasError":true,
   "errorMessage":null,
   "score":100,
   "scoreType":"success",
   "testDetails":null
}
```

**Comment by ic0ns** [comment]
I don't think I can give our customers a useful explanation besides "We could not scan this", at least none they could reasonable understand. Should I just return an "ERROR" placeholder such that we automatically replace the string or should I leave it like it is?

**Comment by Lednerb** [comment]
Du kannst gerne einen Text vorschlagen, wie bspw. "Der Test konnte nicht ausgeführt werden" (ohne Verwendung eines Platzhalters im Text.

vielleicht wäre folgendes Format am idealsten geeignet:

```
"errorMessage": {
   "translationStringId": "TEST_FAILED",
   "placeholders": [
        "ERROR": "TECHNICAL_ANSWER_NOT_FOR_CUSTOMER"
    ]
}
```

Dadurch können wir dem Nutzer den Fall korrekt ausgeben und wir haben für unsere Statistiken den technischen Hintergrund, warum der Test fehlschlug.


Laut Scanner-Sepzifikation MUSS bei `hasError:true` auch eine `errorMessage` im TranslatableMessage Format gesetzt werden.

**Comment by ic0ns** [comment]
Ok, I added a generic error message, but without placeholders. If the text's are in staging we can deploy it imho
