### ISSUE TITLE
ERROR Bleichenbacher Workflow

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#12]
Wir haben sehr viele Log-Meldungen hierzu:

```
ERROR: BleichenbacherAttacker - Could not execute Workflow. Something went wrong... Check the debug output for more information
```

Weitere Informationen kann ich nicht direkt einsehen, was aber auffällig ist, ist dass diese Meldungen anscheinend gebündelt auftreten (siehe Screenshot).

Sollte dies kein `ERROR` sein, sondern "normal", dann bitte Log-Level auf `WARNING` stellen.

![Bildschirmfoto von 2019-09-02 07-44-49](https://user-images.githubusercontent.com/2056876/64092622-da4e7580-cd55-11e9-806d-aaf179307097.png)

Edit:
Im vergangenen Tages-Scan haben wir diesen Fehler insgesamt 492 Mal.

**Comment by ic0ns** [comment]
Reduced log level in develop branch. Should reach master soon
