### ISSUE TITLE
ERROR Padding Oracle

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#13]
Wir erhalten sehr oft folgende Meldung:

```
ERROR: TlsProbe - Encountered an exception while testing for PaddingOracles
```

Sollte dies normal sein, bitte Log Level auf WARNING oder INFO stellen.

Diese Fehlermeldung erscheint 6054 Mal im letzten Tages-Scan.
Sollte die Ausgabe ohnehin keinen Mehrwert im Logging bieten, bitte deaktivieren.

**Comment by ic0ns** [comment]
Reduced log level in develop branch. Should reach master soon
