### ISSUE TITLE
ERROR: PaddingOracleAttacker - Could not execute whole workflow

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#14]
Die oben genannte Fehlermeldung erhalten wir im letzten Tages-Scan 618 Mal.

Falls normal, bitte Log-Level auf WARNING oder INFO stellen oder Ausgabe deaktivieren.

**Comment by ic0ns** [comment]
Reduced log level in develop branch. Should reach master soon
