### ISSUE TITLE
ERROR: TlsTask - Could not execute Workflow.

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#16]
Die oben genannte Fehlermeldung ohne weitere Informationen in der Log-Nachricht erhalten wir im letzten Tages-Scan 1184 Mal.

Falls "normal" Log-Level auf INFO ändern oder deaktivieren.

**Comment by ic0ns** [comment]
Reduced log level in develop branch. Should reach master soon
