### ISSUE TITLE
MAIL-Scanner Übergabe der Domain anstatt URL

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#17]
Die MAIL Scanner haben jeweils den `*.PORT_NO_RESPONSE` Fehler.

Bitte einmal prüfen.

Läuft bei mir weder lokal auf dem Rechner noch auf dem `staging` Server.

**Comment by ic0ns** [comment]
Was genau meinst du?

**Comment by ic0ns** [comment]
nvm sehs gerade in slack

**Comment by Lednerb** [comment]
## Problem gefunden:

Der Start-Parameter lautet `url`, wie im Scanner-Interface definiert.

Übergibt man dem TLS-Scanner allerdings lediglich den Hostname (wie in der `README.md` angegeben), so kann der Hostname offenbar nicht extrahiert werden, obwohl es eine `Success` Response gibt.


Funktioniert: `https://mx1.example.org`
Funktioniert nicht: `mx1.example.org`


==> Readme anpassen und im Falle der MAIL-Scanner die Übergabe der Domain erlauben.

Alternativ könnte ich zwar in der BLA wirklich eine URL übergeben (`http://mx1.example.org`), allerdings ist das dann wirklich verwirrend.

Es ist zwar auch ungünstig, dass im `url` Parameter dann keine URL mitgeliefert werden soll, dies liegt aber am Scanner-Interface Standard und ist meiner Meinung nach das kleinere Übel.

**Comment by ic0ns** [comment]
sollte jetzt in beiden cases funktionieren
