### ISSUE TITLE
Mail-Scanner für SMTP Port 587

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#19]
Wir haben den Scanner `SMTP_TLS` auf Port 25 und `SMTPS_TLS` auf Port 465.

Es fehlt ein Check von Port 587.

--------------------------------

Wie wollen wir das integrieren?

--------------------------------

Beispiel: Mail Server unterstützt lediglich Port 587, dann gibt es 6 _fehlerhafte_ Scans.
Wie sollen die Reports später generiert werden, wenn wir einen Haufen an Scannern haben, die einen `hasError: true` melden?

Das haben wir schon öfter besprochen, der `hasError: true` ist eigentlich richtig, da der Scanner nicht arbeiten kann, wenn ein Port nicht verfügbar ist.
Fehlerhafte Scans aber nicht anzuzeigen, führt auch zu Komplikationen.

Momentan sehe ich dann als einziges die Möglichkeit, in der Webapp explizit ein Handling für die Mail-Scanner zu integrieren.

Probleme gibt es allerdings dann in der BLA, die für die Generierung der PDF-Reports zuständig ist.
Hierfür wäre die naheliegende Lösung, dies ebenfalls in der Webapp zu integrieren, per Print-Stylesheet und dann dem Nutzer anstelle eines PDF-Downloads den Ausdruck zu ermöglichen (der Nutzer muss dann selbst Wissen, dass es möglich ist, in eine PDF zu drucken...).

----------------------------------------
CC: @SniperSister @Skeeve @mniemietz

**Comment by Skeeve** [comment]
Also:

1. DOMXSS
1. HEADER
1. INFOLEAK
1. INI_S
1. PORT
1. TLS
1. VERSION
1. MAIL

Bei Nur-Mail Servern gibt es also fehlerhafte Scans beim Rest (ausser ini_s) . Warum werden die überhaupt angestoßen?

Eigentlich sollten die unzutreffenden Scans gar nicht gemacht werden und auch im Report fehlen. Das sollte aber doch nicht daran festgemacht werden, dass ein Fehler berichtet wird.

Wissen wir nicht im Vorhinein, dass es sich bei einer Adresse um einen Mailserver handelt? Dafür sollte dann nur INI_S und MAIL angestoßen und berichtet werden. Für alles andere sollten alle außer MAIL angestoßen werden.

Bei der Ausgabe sollte dann das was fehlt auch nicht zu Problemen führen.

**Comment by ic0ns** [comment]
naja, der domain validator ist kein port-scanner. Das sind getrennte dinge.

**Comment by Lednerb** [comment]
@Skeeve 
> Bei Nur-Mail Servern gibt es also fehlerhafte Scans beim Rest (ausser ini_s) . Warum werden die überhaupt angestoßen?

Werden sie ja gar nicht. Es dreht sich um die MAIL-Scanner. Siehe Titel.

@Skeeve 
> Wissen wir nicht im Vorhinein, dass es sich bei einer Adresse um einen Mailserver handelt? Dafür sollte dann nur INI_S und MAIL angestoßen und berichtet werden. Für alles andere sollten alle außer MAIL angestoßen werden.

Doch das wissen wir und ist genau der Fall. Darum geht es nicht.


@Skeeve 
> Bei der Ausgabe sollte dann das was fehlt auch nicht zu Problemen führen.

Das ist klar. Es geht auch nicht darum, ob es Probleme gibt oder nicht, sondern wie wir die Ausgabe gestalten wollen.

**Die Frage ist:**
Wollen wir _fehlerhafte_ Scan-Ergebnisse (globales `hasError: true`) dem Nutzer anzeigen oder sollen diese nicht ausgegeben werden?
Dann machen wir das entweder generell oder generell nicht.

Werden die Ergebnisse nicht ausgegeben, kann der Nutzer aber bspw. nicht erkennen, ob bspw. ein Dienst abgestürzt ist und deswegen kein neuer Report angezeigt wird (es würde dann jeweils der letzte erfolgreiche Scan ausgegeben werden).

Daher plädiere ich dafür, dass wir immer das aktuelle Ergebnis zurückliefern, ob mit oder ohne Fehler.

----------------------------

@ic0ns @Skeeve 
> naja, der domain validator ist kein port-scanner. Das sind getrennte dinge.

Genau, hier geht es rein um die MAIL-Scanner, von denen es momentan 6 gibt (`IMAP_TLS`, `SMTP_TLS` und `POP3_TLS` incl. der jeweiligen `*S_TLS` Variante). 

Momentan haben wir folgende Situation:

- `SMTP_TLS` testet den Port 25
- `SMTPS_TLS` testet den Port 465
- **Es gibt keinen SMTP-Test, der Port 587 untersucht.**

**Comment by Skeeve** [comment]
> Daher plädiere ich dafür, dass wir immer das aktuelle Ergebnis zurückliefern, ob mit oder ohne Fehler.

Okay.

**Comment by ic0ns** [comment]
Added Scanner SMTP_MSA_TLS under the url /smtp_msa .
