### ISSUE TITLE
Weißes Kreuz auf rotem Grund bei Nicht-Erreichbarkeit

### ISSUE THREAD

**Issue by PetraStruck** [SIWECOS/WS-TLS-Scanner#23]
Ein Kunde weist darauf hin, dass das weiße Kreuz auf rotem Grund bei Nicht-Erreichbarkeit zu Irritationen führen kann:

"eine nicht Erreichbarkeit eines Serverdienstes stellen Sie mit einem weißen X auf roten Grund da. Dies führt meines Erachtens zu Irritationen, da es ein Schutzlücke suggeriert. Dies ist aber bei abgeschalteten Diensten das genaue Gegenteil. Hier wäre eine neutralere Darstellungsweise übersichtlicher, z.B. Grau.
Ähnlich sieht es im Kopf aus. wo eine 0 mit ein wenig rot im Prozentkreis steht. Ein nicht vorhandener, respektive nicht prüfbarer Dienst mit ganz grauen Kreis und einem - statt der 0 wäre weniger irreführend."

![Teilstück 1 2 2](https://user-images.githubusercontent.com/47851250/73440979-8d95b780-4352-11ea-9f3a-bf23a4ac66f1.jpeg)

![Teilstück 1 2 3](https://user-images.githubusercontent.com/47851250/73440827-4ad3df80-4352-11ea-9c83-37cb6dc80d3c.jpeg)

**Comment by PetraStruck** [comment]
![Teilstück 1 2 2](https://user-images.githubusercontent.com/47851250/73441009-9b4b3d00-4352-11ea-915f-fa479d31b72b.jpeg)

**Comment by ic0ns** [comment]
Hey Petra,
das gehört leider nicht hier hin. Der Scanner meldet nur die Ergebnisse - wie  diese dargestellt werden hat damit nichts zu tun.

**Comment by PetraStruck** [comment]
Wo kann ich das eintragen?

**Comment by ic0ns** [comment]
Also - ich bin mir nicht 100% sicher - aber vermutlich BLA oder Frontend

**Comment by PetraStruck** [comment]
ok, ich schaue mal.
