### ISSUE TITLE
TranslatableMessage Format

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#5]
Der Scanner muss an die neu definierte `TranslatableMessage` angepasst werden, siehe [Scanner-Interface Doku](https://github.com/SIWECOS/siwecos-core-api/tree/develop#translatablemessage-object)

Unterm Strich werden `placeholder` zu `translationStringId` und `values` zu `placeholders` umbenannt.

**Comment by ic0ns** [comment]
Implement in develop branch
