### ISSUE TITLE
Umlaut-URLs prüfen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#6]
Bitte testen, ob URLs mit Sonderzeichen unterstützt werden, ggf. Implementieren.

**Comment by ic0ns** [comment]
Currently not, but I already added support for Unicode Domains in our Internal DevBranch. They will be available in WS-TLS-Scanner once we release the next version

**Comment by ic0ns** [comment]
Fixed in the 3.0_release branch. Will hit the develop branch with the next TLS-Attacker release (3.0)
