### ISSUE TITLE
Überprüfung Request-Interface

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/WS-TLS-Scanner#7]
Der Standard zum Request-Interface wurde um den Parameter `userAgent` erweitert, siehe hier: https://github.com/SIWECOS/siwecos-core-api/blob/develop/SCANNER_INTERFACE-DOCS.md#request-interface

Bitte überprüfen, ob der Scanner diesen Standard einhält, ggf. Implementieren und dann Issue hier schließen.

Vielen Dank.

**Comment by ic0ns** [comment]
UserAgent wird vom TLS-Scanner nicht benötigt (zumindest für die Teile die wir in SIWECOS nutzen). Falls einer mitgegeben wird, wird dieser vom Scanner ignoriert.
